### ISSUE TITLE
Access members in JsonObject via dot notation throws Exception

### ISSUE THREAD

**Issue by injecteer** [vert-x3/vertx-lang-groovy#121]
The last line in code down below throws NoSuchMethodException
```
def json = getJsonObject()

json.getString( 'id' ) // works fine
json[ 'id' ] // works fine
json.id // throws NoSuchMethodException

```
In Vert.x 3.x it used to work.

I should be possible to use the dot-notation for JsonObjects in Groovy.

See also [SO-questrion](https://stackoverflow.com/questions/67511614) for details

**Comment by tsegismont** [comment]
@aaloise any idea about this one?

**Comment by injecteer** [comment]
also I'm missing the good stuff in Groovy of 3.9.x which is not happenning in 4.0.3.
 For example, a `Message<Map>` doesn't work anymore

**Comment by vietj** [comment]
what do you mean by `Message<Map>` ? can you show some code ?

**Comment by injecteer** [comment]
The code down below
```
    vertx.eventBus().localConsumer( "test" ){ Message<Map> msg -> log.info "test << ${msg.body()}" }
    vertx.setTimer( 5_000 ){ vertx.eventBus().send 'test', [ answer:42 ] }
```
produces the exception:
```
15:25:45.444 [vert.x-eventloop-thread-1] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalArgumentException: No message codec for type: class java.util.LinkedHashMap
	at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101)
	at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:232)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:102)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:97)
	at io.vertx.core.eventbus.EventBus$send.call(Unknown Source)
```

whereas in 3.9.7 works like charm:
> INFO io.tope.MyVerticle - test << [answer:42]

**Comment by aaloise** [comment]
Hi. I read the explanation of Jeff Brown at SO and, at least for now, makes sense. The dot notation is only valid if there is a method or field. From some not so obvious reason, it works with Vert.x 3

As for Message<Map>, from my understanding, basically you can say JsonObject is a "map", but not the other way around.

Somehow, in Vert.x 3 Groovy understands under the hood that ```[ answer:42 ]``` is a JsonObject without you having to explicitly sayi it is, like ```[ answer:42 ] as JsonObject```

I think it can be a good starting point if @injecteer could provide a full reproducer with both situations, so we can just switch Vert.x version and investigate the behaviour.

**Comment by injecteer** [comment]
Here's the reproducer

[repro.zip](https://github.com/vert-x3/vertx-lang-groovy/files/6546441/repro.zip)

for version switch simply play with lines in `gradle.properties`:
```
vertxVersion=3.9.7
#vertxVersion=4.0.3
```

**Comment by vietj** [comment]
I think that indeed the as JsonObject like you used in your test is the correct thing to do.

it might seem less magic in Vert.x 4 but this is how Groovy support evolved in Vert.x and it transforming the Map to a JsonObject looks fine to me (`[ answer:42 ] as JsonObject`)

**Comment by vietj** [comment]
I will close this issue as the original issue is not actually an issue.

**Comment by vietj** [comment]
consider opening an issue for the usability issue of the event-bus and if we can have a solution better than `as JsonObject` we could improve this

**Comment by injecteer** [comment]
`[ answer:42 ] as JsonObject` is fine, but you can not use a `Map` as a generic type in a handle()-method signature (see the exception above). And this is a lot worse than an explicit map to JO conversion
