### ISSUE TITLE
Broken links in the generated documentation

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-lang-groovy#13]
The generated groovy doc has some misspelled urls containing `.` instead of `\`.

**Comment by cescoffier** [comment]
So the issue is 'expected' as the targeted file is a Java class (not Groovy), so the link does not work.

I've tried to add extra javadoc directory to the groovydoc plugin, but unfortunately it requires to know the packages (prefix). So we cannot use this.

Another solution is to 'hide' the link using:

```
      private final def @{type.raw} delegate;\n
      public @{constructor}(Object delegate) {\n
    @if{concrete && concreteSuperTypes.size() > 0}
        super((@{type.raw}) delegate);\n
    @end{}
        this.delegate = (@{type.raw}) delegate;\n
      }\n

      public Object getDelegate() {\n
        return delegate;\n
      }\n
```

(changes: make the `delegate` property private, and use Object in the constructor (cast), the `getDelegate` method is unchanged).

Finally, the last solution is to live with these broken links. 

@pmlopes, @vietj, @purplefox : I let you choose.

**Comment by vietj** [comment]
I think we can hide the types, since they are not supposed to be used externally anyway and that would solve the problem.

**Comment by cescoffier** [comment]
ok, will provide this as a PR.
