### ISSUE TITLE
vertx run xxxx.groovy,chinease chars will be garbled,but java file is OK

### ISSUE THREAD

**Issue by aruis** [vert-x3/vertx-lang-groovy#33]
`myverticle.groovy`

void vertxStart() {
    println("\u4f60\u597d")
    println "你好 starting"
}

void vertxStop() {
    println "stopping"
}

`$ vertx run myverticle.groovy`

你好

������ starting

Succeeded in deploying verticle

**Comment by vietj** [comment]
can you print the default JVM locale ?

**Comment by aruis** [comment]
`System.out.println(Locale.getDefault());`
`zh_CN`

**Comment by aruis** [comment]
I think I got the reason. The groovy default [CompilerConfiguration](https://github.com/apache/groovy/blob/master/src/main/org/codehaus/groovy/control/CompilerConfiguration.java) is use `US-ASCII` encoding.
So,I must use a special config set the `groovy.source.encoding` to `UTF-8` like this https://github.com/vert-x3/vertx-lang-groovy/blob/master/src/test/resources/configs/compilerConfiguration.groovy

**Comment by vietj** [comment]
can you provide a PR for this that works for you ?

**Comment by aruis** [comment]
I think the key point for this issue is in groovy language source file. And we can use a config file in vertx to solve it .
So,I think we can close this issue without change any code.
Thanks very much.@vietj.  My English is very poor tolerance.

**Comment by vietj** [comment]
@aruis but vertx-lang-groovy uses implicetely a groovy compiler in the GroovyClassLoader, no ?

**Comment by aruis** [comment]
yes.  I do a PR to fix it in an other way. 
thx ; )
