### ISSUE TITLE
What is groovy Vertx not implementing Java Vertx interface?

### ISSUE THREAD

**Issue by thomashan** [vert-x3/vertx-lang-groovy#35]
Hi there.
I was wondering if there was a reason for the groovy Vertx not implementing the Java Vertx interface?

IMHO, one of the key strengths of groovy is the interchangeability of classes and interfaces. By completely isolating the classes and interfaces we've sandbox everything into Java world and groovy world.

**Comment by vietj** [comment]
hi, we want to investigate using Java interfaces directly in Groovy, I believe there is a thread on vertx-dev google group about that - so it would be best if you discuss this on the vertx-dev forum.

We want to use GitHub issues for bugs instead of not asking questions.

**Comment by thomashan** [comment]
Thanks

**Comment by vietj** [comment]
looking forward to read from you on the list :)
