### ISSUE TITLE
io.vertx.lang.groovy.GroovyVerticle's `start(Future)` has incorrect signature

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/vertx-lang-groovy#39]
In 3.3.3, the method signature for `start(Future)` in io.vertx.lang.groovy.GroovyVerticle only accepts `io.vertx.core.Future` instead of `io.vertx.groovy.core.Future`. This was causing me great pains for a while until I tracked it down.. It is easy to work around by using the implementation of Future from core, but I believe it should be fixed.

This is similar to #28

**Comment by vietj** [comment]
how about overloading it ?

**Comment by InfoSec812** [comment]
Overloading it would work just fine for me... I am just trying to ensure that others don't run into this situation in the future.

**Comment by pmlopes** [comment]
This this issue still apply with the new groovy lang generation?

**Comment by vietj** [comment]
@InfoSec812 right as said @pmlopes , we have actually redone the Groovy support in 3.4.0-SNAPSHOT to use the Java real API in Groovy and generating the Map method as extension, so this concern should not be valid anymore.

Would you mind to check your code with 3.4.0-SNAPSHOT ? there should be an transparent migration path though.
