### ISSUE TITLE
Nested Objects and Arrays materialized in their Java form

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-lang-groovy#5]
Found via the Mongo DB client.  

The fix that was intended to address this has been reverted so I'm recreating this in the correct project.  

The language bindings are intended to present JSON documents in their "native" form to each language. In the Groovy binding (and perhaps others) this is working for the root object, but not for any nested objects and/or arrays. These are instead presented as JsonObject and/or JsonArray instances.

See the following thread for more info https://groups.google.com/forum/#!topic/vertx-dev/StuQ8pv3kWQ.

This gist demonstrates the issue -- https://gist.github.com/sfitts/73d4a2e2229466f5ccd3

**Comment by purplefox** [comment]
@sfitts could you also close this one too if fixed?

**Comment by purplefox** [comment]
I'm going to close this on the assumption it's done. Please re-open if that's not the case.

**Comment by sfitts** [comment]
I'm planning to verify this on the current snapshot this evening.  I'll let
you know if I find any issues.
