### ISSUE TITLE
Groovy object unwrapping causes problems for types with custom codecs when those types implement map.

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-lang-groovy#7]
I've created a custom message codec for `org.bson.Document` and registered it as a global codec.  However, when I attempt to send an instance of `Document` over the event bus is mysteriously gets treated like a `JsonObject` instead.  It turns out that the culprit here is `InternalHelper.unwrapObject`.  This method is called in the Groovy adaptation of the event bus and since `Document` implements the `Map` interface it decides to be helpful and put the map in a JsonObject.

Fixing this is likely to require context which the helper routine doesn't have so I think the fix will involve changing the groovy event bus cover to know when to apply the method and when not to (based on whether the object has a custom codec or not).

**Comment by sfitts** [comment]
I took a look at what it would take to fix this and unfortunately without changing what's visible from the EventBus delegate the best I could come up with was this:

```
  try {
    this.delegate.send(address, message);
  } catch (IllegalArgumentException iae) {
    this.delegate.send(address, InternalHelper.unwrapObject(message));
  }
```

Of course that's ugly.  What would be nicer would be to have a method on EventBus along the lines of `hasMessageCodec(Object message)` which would tell you if the message object can be sent as is or not.  Then you could selectively call `unwrapObject`.  That requires changes in core however.

**Comment by purplefox** [comment]
@sfitts  Sean can you close this if it's now fixed? Thanks
